#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBFONET_CIA_LTDA")]
	public partial class ConexionDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDBDataContext() : 
				base(global::Datos.Properties.Settings.Default.DBFONET_CIA_LTDAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarCliente")]
		public int pa_EditarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, nombres, apellidos, correo, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarCONTRATO_SERVICIO")]
		public int pa_EditarCONTRATO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CONTRATO", DbType="Int")] System.Nullable<int> iD_CONTRATO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PLAN_MEGAS", DbType="Int")] System.Nullable<int> iD_PLAN_MEGAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_INSTALACION", DbType="Int")] System.Nullable<int> iD_INSTALACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CONTRATO, cedula_Cliente, iD_PLAN_MEGAS, iD_INSTALACION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarCORTE_RECONEXION")]
		public int pa_EditarCORTE_RECONEXION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CORTE_RECONEXION", DbType="Int")] System.Nullable<int> iD_CORTE_RECONEXION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CORTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CORTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_RECONEXION", DbType="Date")] System.Nullable<System.DateTime> fecha_RECONEXION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(60)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CORTE_RECONEXION, cedula_Cliente, fECHA_CORTE, fecha_RECONEXION, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarEmpleado")]
		public int pa_EditarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="Date")] System.Nullable<System.DateTime> fecha_Nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Tipo", DbType="Int")] System.Nullable<int> iD_Tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Contrato", DbType="Date")] System.Nullable<System.DateTime> fecha_Contrato, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(20)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Empleado, nombres, apellidos, correo, telefono, direccion, fecha_Nacimiento, iD_Tipo, fecha_Contrato, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarFacturacion")]
		public int pa_EditarFacturacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_FACTURACION", DbType="Int")] System.Nullable<int> iD_FACTURACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Contrato", DbType="Int")] System.Nullable<int> iD_Contrato, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Corte_Reconexion", DbType="Int")] System.Nullable<int> iD_Corte_Reconexion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Pago", DbType="Date")] System.Nullable<System.DateTime> fecha_Pago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_Pago", DbType="Decimal(18,0)")] System.Nullable<decimal> total_Pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_FACTURACION, cedula_Cliente, cedula_Empleado, iD_Contrato, iD_Corte_Reconexion, fecha_Pago, total_Pago);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarFECHA_PAGOS")]
		public int pa_EditarFECHA_PAGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAGO", DbType="Int")] System.Nullable<int> iD_PAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_INSTALACION", DbType="Int")] System.Nullable<int> iD_INSTALACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_PAGO", DbType="Date")] System.Nullable<System.DateTime> fECHA_PAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PLAZO_VENCIDO", DbType="Bit")] System.Nullable<bool> pLAZO_VENCIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACIONES", DbType="VarChar(50)")] string oBSERVACIONES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAGO, cedula_Cliente, iD_INSTALACION, fECHA_PAGO, pLAZO_VENCIDO, oBSERVACIONES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarInstalacion")]
		public int pa_EditarInstalacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Agendar_Instalacion", DbType="Int")] System.Nullable<int> iD_Agendar_Instalacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Instalacion", DbType="Date")] System.Nullable<System.DateTime> fecha_Instalacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendiente", DbType="Bit")] System.Nullable<bool> pendiente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(60)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Agendar_Instalacion, fecha_Instalacion, cedula_Cliente, pendiente, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarPlanMegas")]
		public int pa_EditarPlanMegas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Tipo_Plan_Megas", DbType="Int")] System.Nullable<int> iD_Tipo_Plan_Megas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Megas", DbType="VarChar(10)")] string megas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Costo", DbType="Decimal(18,0)")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Tipo_Plan_Megas, megas, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EditarTipoEmpleado")]
		public int pa_EditarTipoEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Cargo", DbType="Int")] System.Nullable<int> iD_Cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cargo", DbType="VarChar(20)")] string cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Cargo, cargo, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarCliente")]
		public int pa_EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarCONTRATO_SERVICIO")]
		public int pa_EliminarCONTRATO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CONTRATO", DbType="Int")] System.Nullable<int> iD_CONTRATO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CONTRATO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarCORTE_RECONEXION")]
		public int pa_EliminarCORTE_RECONEXION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_CORTE_RECONEXION", DbType="Int")] System.Nullable<int> iD_CORTE_RECONEXION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_CORTE_RECONEXION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarEmpleado")]
		public int pa_EliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Empleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarFacturacion")]
		public int pa_EliminarFacturacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_FACTURACION", DbType="Int")] System.Nullable<int> iD_FACTURACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_FACTURACION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarFECHA_PAGOS")]
		public int pa_EliminarFECHA_PAGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PAGO", DbType="Int")] System.Nullable<int> iD_PAGO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_PAGO);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarInstalacion")]
		public int pa_EliminarInstalacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Agendar_Instalacion", DbType="Int")] System.Nullable<int> iD_Agendar_Instalacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Agendar_Instalacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarPlanMegas")]
		public int pa_EliminarPlanMegas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Tipo_Plan_Megas", DbType="Int")] System.Nullable<int> iD_Tipo_Plan_Megas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Tipo_Plan_Megas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_EliminarTipoEmpleado")]
		public int pa_EliminarTipoEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Cargo", DbType="Int")] System.Nullable<int> iD_Cargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Cargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarCliente")]
		public int pa_InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, nombres, apellidos, correo, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarCONTRATO_SERVICIO")]
		public int pa_InsertarCONTRATO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_PLAN_MEGAS", DbType="Int")] System.Nullable<int> iD_PLAN_MEGAS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_INSTALACION", DbType="Int")] System.Nullable<int> iD_INSTALACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, iD_PLAN_MEGAS, iD_INSTALACION);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarCORTE_RECONEXION")]
		public int pa_InsertarCORTE_RECONEXION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_CORTE", DbType="Date")] System.Nullable<System.DateTime> fecha_CORTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_RECONEXION", DbType="Date")] System.Nullable<System.DateTime> fecha_RECONEXION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(60)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, fecha_CORTE, fecha_RECONEXION, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarEmpleado")]
		public int pa_InsertarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombres", DbType="VarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apellidos", DbType="VarChar(50)")] string apellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Nacimiento", DbType="Date")] System.Nullable<System.DateTime> fecha_Nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Tipo", DbType="Int")] System.Nullable<int> iD_Tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Contrato", DbType="Date")] System.Nullable<System.DateTime> fecha_Contrato, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(20)")] string contraseña)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Empleado, nombres, apellidos, correo, telefono, direccion, fecha_Nacimiento, iD_Tipo, fecha_Contrato, contraseña);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarFacturacion")]
		public int pa_InsertarFacturacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Contrato", DbType="Int")] System.Nullable<int> iD_Contrato, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Corte_Reconexion", DbType="Int")] System.Nullable<int> iD_Corte_Reconexion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Pago", DbType="Date")] System.Nullable<System.DateTime> fecha_Pago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total_Pago", DbType="Decimal(18,0)")] System.Nullable<decimal> total_Pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, cedula_Empleado, iD_Contrato, iD_Corte_Reconexion, fecha_Pago, total_Pago);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarFECHA_PAGOS")]
		public int pa_InsertarFECHA_PAGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_INSTALACION", DbType="Int")] System.Nullable<int> iD_INSTALACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_PAGO", DbType="Date")] System.Nullable<System.DateTime> fECHA_PAGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PLAZO_VENCIDO", DbType="Bit")] System.Nullable<bool> pLAZO_VENCIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACIONES", DbType="VarChar(50)")] string oBSERVACIONES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, iD_INSTALACION, fECHA_PAGO, pLAZO_VENCIDO, oBSERVACIONES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarInstalacion")]
		public int pa_InsertarInstalacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Instalacion", DbType="Date")] System.Nullable<System.DateTime> fecha_Instalacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendiente", DbType="Bit")] System.Nullable<bool> pendiente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Observaciones", DbType="VarChar(60)")] string observaciones)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, fecha_Instalacion, pendiente, observaciones);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarPlanMegas")]
		public int pa_InsertarPlanMegas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Megas", DbType="VarChar(10)")] string megas, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Costo", DbType="Decimal(18,0)")] System.Nullable<decimal> costo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), megas, costo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_InsertarTipoEmpleado")]
		public int pa_InsertarTipoEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cargo", DbType="VarChar(20)")] string cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargo, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarCliente")]
		public ISingleResult<pa_MostrarClienteResult> pa_MostrarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente);
			return ((ISingleResult<pa_MostrarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarCONTRATO_SERVICIO")]
		public ISingleResult<pa_MostrarCONTRATO_SERVICIOResult> pa_MostrarCONTRATO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente);
			return ((ISingleResult<pa_MostrarCONTRATO_SERVICIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarCORTE_RECONEXION")]
		public ISingleResult<pa_MostrarCORTE_RECONEXIONResult> pa_MostrarCORTE_RECONEXION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CORTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CORTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_RECONEXION", DbType="Date")] System.Nullable<System.DateTime> fecha_RECONEXION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, fECHA_CORTE, fecha_RECONEXION);
			return ((ISingleResult<pa_MostrarCORTE_RECONEXIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarEmpleado")]
		public ISingleResult<pa_MostrarEmpleadoResult> pa_MostrarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Empleado);
			return ((ISingleResult<pa_MostrarEmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarFacturacion")]
		public ISingleResult<pa_MostrarFacturacionResult> pa_MostrarFacturacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Empleado", DbType="VarChar(10)")] string cedula_Empleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha_Pago", DbType="Date")] System.Nullable<System.DateTime> fecha_Pago)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, cedula_Empleado, fecha_Pago);
			return ((ISingleResult<pa_MostrarFacturacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarFECHA_PAGOS")]
		public ISingleResult<pa_MostrarFECHA_PAGOSResult> pa_MostrarFECHA_PAGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente);
			return ((ISingleResult<pa_MostrarFECHA_PAGOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarInstalaciones")]
		public ISingleResult<pa_MostrarInstalacionesResult> pa_MostrarInstalaciones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula_Cliente", DbType="VarChar(10)")] string cedula_Cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_INSTALACION", DbType="Date")] System.Nullable<System.DateTime> fECHA_INSTALACION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula_Cliente, fECHA_INSTALACION);
			return ((ISingleResult<pa_MostrarInstalacionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarPlanMegas")]
		public ISingleResult<pa_MostrarPlanMegasResult> pa_MostrarPlanMegas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Megas", DbType="VarChar(10)")] string megas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), megas);
			return ((ISingleResult<pa_MostrarPlanMegasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pa_MostrarTipoEmpleado")]
		public ISingleResult<pa_MostrarTipoEmpleadoResult> pa_MostrarTipoEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cargo", DbType="VarChar(20)")] string cargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cargo);
			return ((ISingleResult<pa_MostrarTipoEmpleadoResult>)(result.ReturnValue));
		}
	}
	
	public partial class pa_MostrarClienteResult
	{
		
		private string _CEDULA_CLIENTE;
		
		private string _NOMBRES;
		
		private string _APELLIDOS;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		public pa_MostrarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(50)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(50)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(50)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(10)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(50)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarCONTRATO_SERVICIOResult
	{
		
		private int _ID_CONTRTATO;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<int> _ID_PLAN_MEGAS;
		
		private System.Nullable<int> _ID_INSTALACION;
		
		public pa_MostrarCONTRATO_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTRTATO", DbType="Int NOT NULL")]
		public int ID_CONTRTATO
		{
			get
			{
				return this._ID_CONTRTATO;
			}
			set
			{
				if ((this._ID_CONTRTATO != value))
				{
					this._ID_CONTRTATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PLAN_MEGAS", DbType="Int")]
		public System.Nullable<int> ID_PLAN_MEGAS
		{
			get
			{
				return this._ID_PLAN_MEGAS;
			}
			set
			{
				if ((this._ID_PLAN_MEGAS != value))
				{
					this._ID_PLAN_MEGAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSTALACION", DbType="Int")]
		public System.Nullable<int> ID_INSTALACION
		{
			get
			{
				return this._ID_INSTALACION;
			}
			set
			{
				if ((this._ID_INSTALACION != value))
				{
					this._ID_INSTALACION = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarCORTE_RECONEXIONResult
	{
		
		private int _ID_CORTE_RECONEXION;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<System.DateTime> _FECHA_CORTE;
		
		private System.Nullable<System.DateTime> _FECHA_RECONEXION;
		
		private string _OBSERVACIONES;
		
		public pa_MostrarCORTE_RECONEXIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CORTE_RECONEXION", DbType="Int NOT NULL")]
		public int ID_CORTE_RECONEXION
		{
			get
			{
				return this._ID_CORTE_RECONEXION;
			}
			set
			{
				if ((this._ID_CORTE_RECONEXION != value))
				{
					this._ID_CORTE_RECONEXION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CORTE", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_CORTE
		{
			get
			{
				return this._FECHA_CORTE;
			}
			set
			{
				if ((this._FECHA_CORTE != value))
				{
					this._FECHA_CORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_RECONEXION", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_RECONEXION
		{
			get
			{
				return this._FECHA_RECONEXION;
			}
			set
			{
				if ((this._FECHA_RECONEXION != value))
				{
					this._FECHA_RECONEXION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(60)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarEmpleadoResult
	{
		
		private string _CEDULA_EMPLEADO;
		
		private string _NOMBRES;
		
		private string _APELLIDOS;
		
		private string _CORREO;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		private System.Nullable<System.DateTime> _FECHA_NACIMIENTO;
		
		private System.Nullable<int> _ID_TIPO;
		
		private System.Nullable<System.DateTime> _FECHA_CONTRATO;
		
		private string _CONTRASEÑA;
		
		public pa_MostrarEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_EMPLEADO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CEDULA_EMPLEADO
		{
			get
			{
				return this._CEDULA_EMPLEADO;
			}
			set
			{
				if ((this._CEDULA_EMPLEADO != value))
				{
					this._CEDULA_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(50)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(50)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(50)")]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(10)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(50)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO", DbType="Int")]
		public System.Nullable<int> ID_TIPO
		{
			get
			{
				return this._ID_TIPO;
			}
			set
			{
				if ((this._ID_TIPO != value))
				{
					this._ID_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CONTRATO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_CONTRATO
		{
			get
			{
				return this._FECHA_CONTRATO;
			}
			set
			{
				if ((this._FECHA_CONTRATO != value))
				{
					this._FECHA_CONTRATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASEÑA", DbType="VarChar(20)")]
		public string CONTRASEÑA
		{
			get
			{
				return this._CONTRASEÑA;
			}
			set
			{
				if ((this._CONTRASEÑA != value))
				{
					this._CONTRASEÑA = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarFacturacionResult
	{
		
		private int _ID_FACTURA;
		
		private string _CEDULA_CLIENTE;
		
		private string _CEDULA_EMPLEADO;
		
		private System.Nullable<int> _ID_CONTRATO;
		
		private System.Nullable<int> _ID_CORTE_RECONEXION;
		
		private System.Nullable<System.DateTime> _FECHA_PAGO;
		
		private System.Nullable<decimal> _TOTAL_PAGO;
		
		public pa_MostrarFacturacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FACTURA", DbType="Int NOT NULL")]
		public int ID_FACTURA
		{
			get
			{
				return this._ID_FACTURA;
			}
			set
			{
				if ((this._ID_FACTURA != value))
				{
					this._ID_FACTURA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_EMPLEADO", DbType="VarChar(10)")]
		public string CEDULA_EMPLEADO
		{
			get
			{
				return this._CEDULA_EMPLEADO;
			}
			set
			{
				if ((this._CEDULA_EMPLEADO != value))
				{
					this._CEDULA_EMPLEADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CONTRATO", DbType="Int")]
		public System.Nullable<int> ID_CONTRATO
		{
			get
			{
				return this._ID_CONTRATO;
			}
			set
			{
				if ((this._ID_CONTRATO != value))
				{
					this._ID_CONTRATO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CORTE_RECONEXION", DbType="Int")]
		public System.Nullable<int> ID_CORTE_RECONEXION
		{
			get
			{
				return this._ID_CORTE_RECONEXION;
			}
			set
			{
				if ((this._ID_CORTE_RECONEXION != value))
				{
					this._ID_CORTE_RECONEXION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PAGO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_PAGO
		{
			get
			{
				return this._FECHA_PAGO;
			}
			set
			{
				if ((this._FECHA_PAGO != value))
				{
					this._FECHA_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PAGO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TOTAL_PAGO
		{
			get
			{
				return this._TOTAL_PAGO;
			}
			set
			{
				if ((this._TOTAL_PAGO != value))
				{
					this._TOTAL_PAGO = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarFECHA_PAGOSResult
	{
		
		private int _ID_PAGO;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<int> _ID_INSTALACION;
		
		private System.Nullable<System.DateTime> _FECHA_PAGO;
		
		private bool _PLAZO_VENCIDO;
		
		private string _OBSERVACIONES;
		
		public pa_MostrarFECHA_PAGOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PAGO", DbType="Int NOT NULL")]
		public int ID_PAGO
		{
			get
			{
				return this._ID_PAGO;
			}
			set
			{
				if ((this._ID_PAGO != value))
				{
					this._ID_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSTALACION", DbType="Int")]
		public System.Nullable<int> ID_INSTALACION
		{
			get
			{
				return this._ID_INSTALACION;
			}
			set
			{
				if ((this._ID_INSTALACION != value))
				{
					this._ID_INSTALACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PAGO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_PAGO
		{
			get
			{
				return this._FECHA_PAGO;
			}
			set
			{
				if ((this._FECHA_PAGO != value))
				{
					this._FECHA_PAGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAZO_VENCIDO", DbType="Bit NOT NULL")]
		public bool PLAZO_VENCIDO
		{
			get
			{
				return this._PLAZO_VENCIDO;
			}
			set
			{
				if ((this._PLAZO_VENCIDO != value))
				{
					this._PLAZO_VENCIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(50)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarInstalacionesResult
	{
		
		private int _ID_INSTALACION;
		
		private string _CEDULA_CLIENTE;
		
		private System.Nullable<System.DateTime> _FECHA_INSTALACION;
		
		private bool _PENDIENTE;
		
		private string _OBSERVACIONES;
		
		public pa_MostrarInstalacionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INSTALACION", DbType="Int NOT NULL")]
		public int ID_INSTALACION
		{
			get
			{
				return this._ID_INSTALACION;
			}
			set
			{
				if ((this._ID_INSTALACION != value))
				{
					this._ID_INSTALACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_CLIENTE", DbType="VarChar(10)")]
		public string CEDULA_CLIENTE
		{
			get
			{
				return this._CEDULA_CLIENTE;
			}
			set
			{
				if ((this._CEDULA_CLIENTE != value))
				{
					this._CEDULA_CLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INSTALACION", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_INSTALACION
		{
			get
			{
				return this._FECHA_INSTALACION;
			}
			set
			{
				if ((this._FECHA_INSTALACION != value))
				{
					this._FECHA_INSTALACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PENDIENTE", DbType="Bit NOT NULL")]
		public bool PENDIENTE
		{
			get
			{
				return this._PENDIENTE;
			}
			set
			{
				if ((this._PENDIENTE != value))
				{
					this._PENDIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACIONES", DbType="VarChar(60)")]
		public string OBSERVACIONES
		{
			get
			{
				return this._OBSERVACIONES;
			}
			set
			{
				if ((this._OBSERVACIONES != value))
				{
					this._OBSERVACIONES = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarPlanMegasResult
	{
		
		private int _ID_PLAN_MEGAS;
		
		private string _MEGAS;
		
		private System.Nullable<decimal> _COSTO;
		
		public pa_MostrarPlanMegasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PLAN_MEGAS", DbType="Int NOT NULL")]
		public int ID_PLAN_MEGAS
		{
			get
			{
				return this._ID_PLAN_MEGAS;
			}
			set
			{
				if ((this._ID_PLAN_MEGAS != value))
				{
					this._ID_PLAN_MEGAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEGAS", DbType="VarChar(10)")]
		public string MEGAS
		{
			get
			{
				return this._MEGAS;
			}
			set
			{
				if ((this._MEGAS != value))
				{
					this._MEGAS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COSTO", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> COSTO
		{
			get
			{
				return this._COSTO;
			}
			set
			{
				if ((this._COSTO != value))
				{
					this._COSTO = value;
				}
			}
		}
	}
	
	public partial class pa_MostrarTipoEmpleadoResult
	{
		
		private int _ID_TIPO;
		
		private string _CARGO;
		
		private string _DESCRIPCION;
		
		public pa_MostrarTipoEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO", DbType="Int NOT NULL")]
		public int ID_TIPO
		{
			get
			{
				return this._ID_TIPO;
			}
			set
			{
				if ((this._ID_TIPO != value))
				{
					this._ID_TIPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARGO", DbType="VarChar(20)")]
		public string CARGO
		{
			get
			{
				return this._CARGO;
			}
			set
			{
				if ((this._CARGO != value))
				{
					this._CARGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
